### ISSUE TITLE
Asynchronous methods

### ISSUE THREAD

**Issue by samjmckenzie** [epeli/immer-reducer#10]
Was wondering if there was a way to implement asynchronous methods using thunk?

**Comment by epeli** [comment]
Not really since immer-reducer is basically just a way to define the reducer function.

This is 

```js
class Reducer extends ImmerReducer {
    setName(name) {
        this.draftState.name = name;
    }
}
```

basically same as

```js
function reducer(action, state) {
  switch (action.name) {
    case "SET_NAME":
      return {...state, name: action.name};
    default:
      return state;
  }
}
```

In theory it could be possible to make some exception for `createActionCreators()`  that generates thunks or something but async actions are whole new can of worms and I like that immer-reducer focuses doing only thing well.

That being said immer-reducer works well with the `redux-thunk` module. I've also heard people using this with redux-observable. I personally use [this](https://github.com/epeli/redux-stack#makethunkcreatormapstore-function) thunk creating wrapper which helps with TS typing.

**Comment by samjmckenzie** [comment]
Ah right, I understand now. Thanks!
